/*-
 * Copyright (c) 2020, 2025 Oracle and/or its affiliates. All rights reserved.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at
 *  https://oss.oracle.com/licenses/upl/
 */

namespace Oracle.NoSQL.SDK
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Reflection;

    // Names of regions are the same as in OCI C# SDK.

    /// <summary>
    /// Cloud Service only.  Represents the region in the Oracle Cloud
    /// Infrastructure.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The class contains the regions in the Oracle Cloud Infrastructure at
    /// the time of this release.  The Oracle NoSQL Database Cloud Service is
    /// not available in all of these regions.  For a definitive list of regions
    /// in which the Oracle NoSQL Database Cloud Service is available see
    /// <see href="https://www.oracle.com/cloud/data-regions.html">
    /// Data Regions for Platform and Infrastructure Services
    /// </see>.
    /// </para>
    /// <para>
    /// The applications cannot construct instances of this class and instead
    /// should use one of predefined read-only instances such as
    /// <see cref="Region.AP_MUMBAI_1"/>, <see cref="Region.US_PHOENIX_1"/>,
    /// etc.
    /// </para>
    /// <para>
    /// The <see cref="Region"/> instance can be provided as
    /// <see cref="NoSQLConfig.Region"/> property when creating
    /// <see cref="NoSQLClient"/> instance.  The region determines the
    /// endpoint with the <see cref="NoSQLClient"/> instance will
    /// communicate.  Note that you may not specify both
    /// <see cref="NoSQLConfig.Region"/> and
    /// <see cref="NoSQLConfig.Endpoint"/> properties.
    /// </para>
    /// <para>
    /// The string-based endpoints associated with the regions for the Oracle
    /// NoSQL Database Cloud Service are in the format
    /// <em>https://nosql.{regionId}.oci.{secondLevelDomain}</em>.
    /// </para>
    /// <para>
    /// The region id is defined for each region and is available via
    /// <see cref="RegionId"/> property.  The value of the region id can be
    /// also determined from its field name by lower-casing it and replacing
    /// <em>_</em> with <em>-</em>.  For example, the region id for
    /// <see cref="Region.AP_SEOUL_1"/> is <em>ap-seoul-1</em>.
    /// </para>
    /// <para>
    /// The examples of known second level
    /// domains include:
    /// <list type="bullet">
    /// <item><description><em>oraclecloud.com</em></description></item>
    /// <item><description><em>oraclegovcloud.com</em></description></item>
    /// <item><description><em>oraclegovcloud.uk</em></description></item>
    /// <item><description><em>oraclecloud8.com</em></description></item>
    /// </list>
    /// </para>
    /// <para>
    /// For example, the endpoint for <see cref="Region.US_ASHBURN_1"/> region
    /// would be <em>https://nosql.us-ashburn-1.oci.oraclecloud.com</em>.
    /// </para>
    /// <para>
    /// If the Oracle NoSQL Database Cloud Service becomes available in a
    /// region not yet defined here, you may connect to that region by using
    /// its endpoint constructed by the rules above and setting it as
    /// <see cref="NoSQLConfig.Endpoint"/>.
    /// </para>
    /// <para>
    /// For more information about Oracle Cloud Infrastructure regions see
    /// <see href="https://docs.cloud.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm">
    /// Regions and Availability Domains
    /// </see>
    /// </para>
    /// </remarks>
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    public class Region
    {
        private class Realm
        {
            internal Realm(string realmId, string secondLevelDomain)
            {
                RealmId = realmId;
                SecondLevelDomain = secondLevelDomain;
            }

            internal string RealmId { get; }

            internal string SecondLevelDomain { get; }
        }

        // === Begin autogenerated realms ===
        private static readonly Realm OC0 = new Realm("oc0",
            "oraclecloud0.com");

        private static readonly Realm OC1 = new Realm("oc1",
            "oraclecloud.com");

        private static readonly Realm OC2 = new Realm("oc2",
            "oraclegovcloud.com");

        private static readonly Realm OC3 = new Realm("oc3",
            "oraclegovcloud.com");

        private static readonly Realm OC4 = new Realm("oc4",
            "oraclegovcloud.uk");

        private static readonly Realm OC5 = new Realm("oc5",
            "oraclecloud5.com");

        private static readonly Realm OC6 = new Realm("oc6",
            "oraclecloud.ic.gov");

        private static readonly Realm OC8 = new Realm("oc8",
            "oraclecloud8.com");

        private static readonly Realm OC9 = new Realm("oc9",
            "oraclecloud9.com");

        private static readonly Realm OC10 = new Realm("oc10",
            "oraclecloud10.com");

        private static readonly Realm OC11 = new Realm("oc11",
            "oraclecloud.smil.mil");

        private static readonly Realm OC12 = new Realm("oc12",
            "oracledodcloud.ic.gov");

        private static readonly Realm OC14 = new Realm("oc14",
            "oraclecloud14.com");

        private static readonly Realm OC15 = new Realm("oc15",
            "oraclecloud15.com");

        private static readonly Realm OC16 = new Realm("oc16",
            "oraclecloud16.com");

        private static readonly Realm OC17 = new Realm("oc17",
            "oraclecloud17.com");

        private static readonly Realm OC19 = new Realm("oc19",
            "oraclecloud.eu");

        private static readonly Realm OC20 = new Realm("oc20",
            "oraclecloud20.com");

        private static readonly Realm OC21 = new Realm("oc21",
            "oraclecloud21.com");

        private static readonly Realm OC22 = new Realm("oc22",
            "psn-pco.it");

        private static readonly Realm OC23 = new Realm("oc23",
            "oraclecloud23.com");

        private static readonly Realm OC24 = new Realm("oc24",
            "oraclecloud24.com");

        private static readonly Realm OC25 = new Realm("oc25",
            "nricloud.jp");

        private static readonly Realm OC26 = new Realm("oc26",
            "oraclecloud26.com");

        private static readonly Realm OC27 = new Realm("oc27",
            "oraclecloud27.com");

        private static readonly Realm OC28 = new Realm("oc28",
            "oraclecloud28.com");

        private static readonly Realm OC29 = new Realm("oc29",
            "oraclecloud29.com");

        private static readonly Realm OC31 = new Realm("oc31",
            "sovereigncloud.nz");

        private static readonly Realm OC32 = new Realm("oc32",
            "oraclecloud32.com");

        private static readonly Realm OC35 = new Realm("oc35",
            "oraclecloud35.com");

        private static readonly Realm OC36 = new Realm("oc36",
            "stccloud.com");

        private static readonly Realm OC39 = new Realm("oc39",
            "oraclecloud39.com");

        private static readonly Realm OC40 = new Realm("oc40",
            "jpsovereigncloud.jp");

        private static readonly Realm OC41 = new Realm("oc41",
            "dutechcloud.ae");

        private static readonly Realm OC42 = new Realm("oc42",
            "oraclecloud42.com");

        private static readonly Realm OC43 = new Realm("oc43",
            "thaiaiscloud.com");

        private static readonly Realm OC45 = new Realm("oc45",
            "q8-onecloud.com");

        private static readonly Realm OC46 = new Realm("oc46",
            "oraclecloud46.com");

        private static readonly Realm OC47 = new Realm("oc47",
            "oraclecloud47.com");

        private static readonly Realm OC50 = new Realm("oc50",
            "opencanvas.jp");

        private static readonly Realm OC51 = new Realm("oc51",
            "oraclecloud51.com");

        private static readonly Realm OC52 = new Realm("oc52",
            "oraclecloud52.com");

        private static readonly Realm OC54 = new Realm("oc54",
            "portalclarocco.com.br");

        private static readonly Realm OC55 = new Realm("oc55",
            "svcl.jp");

        private static readonly Realm OC57 = new Realm("oc57",
            "eonecloud.com");

        private static readonly Realm OC60 = new Realm("oc60",
            "oraclecloud60.com");

        private static readonly Realm OC61 = new Realm("oc61",
            "oraclecloud61.com");

        private static readonly Realm OC62 = new Realm("oc62",
            "oraclecloud62.com");

        private static readonly Realm OC64 = new Realm("oc64",
            "absonne4cloud.com");

        private static readonly Realm OC88 = new Realm("oc88",
            "oraclecloud88.com");

        // === End autogenerated realms ===

        private readonly Realm realm;

        private Region(string regionId, string regionCode, Realm realm)
        {
            RegionId = regionId;
            RegionCode = regionCode;
            this.realm = realm;
        }

        /// <summary>
        /// Gets the region id.
        /// </summary>
        /// <value>
        /// The region id as described in the <see cref="Region"/> remarks
        /// section.
        /// </value>
        public string RegionId { get; }

        /// <summary>
        /// Gets the region code.
        /// </summary>
        /// <value>
        /// Region code (which may also be referred to as region key), which
        /// is a 3-letter identifier for each region.  Note that the this
        /// value is in lower case.
        /// </value>
        public string RegionCode { get; }

        /// <summary>
        /// Get the region second level domain.
        /// </summary>
        /// <value>
        /// The second level domain as described in the <see cref="Region"/>
        /// remarks section.
        /// </value>
        public string SecondLevelDomain => realm.SecondLevelDomain;

        /// <summary>
        /// Gets the region endpoint.
        /// </summary>
        /// <value>
        /// The region endpoint constructed as described in the
        /// <see cref="Region"/> remarks section.
        /// </value>
        public string Endpoint =>
            $"https://nosql.{RegionId}.oci.{realm.SecondLevelDomain}";

        /// <summary>
        /// Converts the value of this instance to string.
        /// </summary>
        /// <returns>The region id.</returns>
        public override string ToString() => RegionId;

        /// <summary>
        /// Returns the region associated with the specified region id.
        /// </summary>
        /// <param name="regionId">The region id.</param>
        /// <returns>The region that has its region id equal to
        /// <paramref name="regionId"/>, case-insensitive.</returns>
        /// <exception cref="ArgumentException">If the region with the
        /// specified <paramref name="regionId"/> could not be found.
        /// </exception>
        /// <seealso cref="RegionId"/>
        public static Region FromRegionId(string regionId)
        {
            if (regionId == null)
            {
                throw new ArgumentNullException(nameof(regionId));
            }

            string fieldName = regionId.Replace('-', '_').ToUpper();
            var field = typeof(Region).GetField(fieldName,
                BindingFlags.Public | BindingFlags.Static);

            if (field == null || field.FieldType != typeof(Region))
            {
                throw new ArgumentException(
                    $"Could not find region with region id {regionId}",
                    nameof(regionId));
            }

            var region = (Region)field.GetValue(null);
            Debug.Assert(region != null);
            return region;
        }

        /// <summary>
        /// Returns the region associated with the specified region code or
        /// region id.
        /// </summary>
        /// <param name="regionCodeOrId">The region code or region id used to
        /// search for the region.</param>
        /// <returns>The region that has its region code or region id equal to
        /// <paramref name="regionCodeOrId"/>, case-insensitive.</returns>
        /// <exception cref="ArgumentException">If the region with the
        /// specified code or id equal to <paramref name="regionCodeOrId"/>
        /// could not be found.
        /// </exception>
        /// <seealso cref="RegionId"/>
        /// <seealso cref="RegionCode"/>
        public static Region FromRegionCodeOrId(string regionCodeOrId)
        {
            var fields = typeof(Region).GetFields(
                BindingFlags.Public | BindingFlags.Static);

            foreach (var field in fields)
            {
                if (field.FieldType != typeof(Region))
                {
                    continue;
                }

                var region = (Region)field.GetValue(null);
                Debug.Assert(region != null);

                if (string.Equals(region.RegionCode, regionCodeOrId,
                        StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(region.RegionId, regionCodeOrId,
                        StringComparison.OrdinalIgnoreCase))
                {
                    return region;
                }
            }

            throw new ArgumentException(
                "Could not find region from region code or region id " +
                regionCodeOrId, nameof(regionCodeOrId));
        }

        /// <summary>
        /// Returns the collection of all regions defined in this class.
        /// </summary>
        /// <value>
        /// All regions defined in this class as a read-only collection.
        /// </value>
        public static IReadOnlyCollection<Region> Values
        {
            get
            {
                var result = new List<Region>();
                var fields = typeof(Region).GetFields(
                    BindingFlags.Public | BindingFlags.Static);

                foreach (var regionField in fields)
                {
                    if (regionField.FieldType != typeof(Region))
                    {
                        continue;
                    }

                    var region = (Region)regionField.GetValue(null);
                    Debug.Assert(region != null);

                    result.Add(region);
                }

                return result;
            }
        }

        // === Begin autogenerated regions ===
        /// <summary>
        /// Realm: OC0, RegionID: uk-london-9, RegionKey: aej
        /// </summary>
        public static readonly Region UK_LONDON_9 = new Region(
            "uk-london-9", "aej", OC0);

        /// <summary>
        /// Realm: OC0, RegionID: us-renton-1, RegionKey: rnt
        /// </summary>
        public static readonly Region US_RENTON_1 = new Region(
            "us-renton-1", "rnt", OC0);

        /// <summary>
        /// Realm: OC0, RegionID: us-scottsdale-1, RegionKey: scf
        /// </summary>
        public static readonly Region US_SCOTTSDALE_1 = new Region(
            "us-scottsdale-1", "scf", OC0);

        /// <summary>
        /// Realm: OC1, RegionID: af-casablanca-1, RegionKey: lej
        /// </summary>
        public static readonly Region AF_CASABLANCA_1 = new Region(
            "af-casablanca-1", "lej", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: af-johannesburg-1, RegionKey: jnb
        /// </summary>
        public static readonly Region AF_JOHANNESBURG_1 = new Region(
            "af-johannesburg-1", "jnb", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: af-nairobi-1, RegionKey: kxt
        /// </summary>
        public static readonly Region AF_NAIROBI_1 = new Region(
            "af-nairobi-1", "kxt", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-batam-1, RegionKey: hsg
        /// </summary>
        public static readonly Region AP_BATAM_1 = new Region(
            "ap-batam-1", "hsg", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-chennai-1, RegionKey: des
        /// </summary>
        public static readonly Region AP_CHENNAI_1 = new Region(
            "ap-chennai-1", "des", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-chuncheon-1, RegionKey: yny
        /// </summary>
        public static readonly Region AP_CHUNCHEON_1 = new Region(
            "ap-chuncheon-1", "yny", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-delhi-1, RegionKey: onm
        /// </summary>
        public static readonly Region AP_DELHI_1 = new Region(
            "ap-delhi-1", "onm", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-hyderabad-1, RegionKey: hyd
        /// </summary>
        public static readonly Region AP_HYDERABAD_1 = new Region(
            "ap-hyderabad-1", "hyd", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-kulai-1, RegionKey: fyv
        /// </summary>
        public static readonly Region AP_KULAI_1 = new Region(
            "ap-kulai-1", "fyv", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-kulai-2, RegionKey: jbp
        /// </summary>
        public static readonly Region AP_KULAI_2 = new Region(
            "ap-kulai-2", "jbp", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-melbourne-1, RegionKey: mel
        /// </summary>
        public static readonly Region AP_MELBOURNE_1 = new Region(
            "ap-melbourne-1", "mel", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-mumbai-1, RegionKey: bom
        /// </summary>
        public static readonly Region AP_MUMBAI_1 = new Region(
            "ap-mumbai-1", "bom", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-osaka-1, RegionKey: kix
        /// </summary>
        public static readonly Region AP_OSAKA_1 = new Region(
            "ap-osaka-1", "kix", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-seoul-1, RegionKey: icn
        /// </summary>
        public static readonly Region AP_SEOUL_1 = new Region(
            "ap-seoul-1", "icn", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-singapore-1, RegionKey: sin
        /// </summary>
        public static readonly Region AP_SINGAPORE_1 = new Region(
            "ap-singapore-1", "sin", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-singapore-2, RegionKey: xsp
        /// </summary>
        public static readonly Region AP_SINGAPORE_2 = new Region(
            "ap-singapore-2", "xsp", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-sydney-1, RegionKey: syd
        /// </summary>
        public static readonly Region AP_SYDNEY_1 = new Region(
            "ap-sydney-1", "syd", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ap-tokyo-1, RegionKey: nrt
        /// </summary>
        public static readonly Region AP_TOKYO_1 = new Region(
            "ap-tokyo-1", "nrt", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ca-montreal-1, RegionKey: yul
        /// </summary>
        public static readonly Region CA_MONTREAL_1 = new Region(
            "ca-montreal-1", "yul", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: ca-toronto-1, RegionKey: yyz
        /// </summary>
        public static readonly Region CA_TORONTO_1 = new Region(
            "ca-toronto-1", "yyz", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-amsterdam-1, RegionKey: ams
        /// </summary>
        public static readonly Region EU_AMSTERDAM_1 = new Region(
            "eu-amsterdam-1", "ams", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-dublin-3, RegionKey: zqo
        /// </summary>
        public static readonly Region EU_DUBLIN_3 = new Region(
            "eu-dublin-3", "zqo", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-frankfurt-1, RegionKey: fra
        /// </summary>
        public static readonly Region EU_FRANKFURT_1 = new Region(
            "eu-frankfurt-1", "fra", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-madrid-1, RegionKey: mad
        /// </summary>
        public static readonly Region EU_MADRID_1 = new Region(
            "eu-madrid-1", "mad", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-madrid-3, RegionKey: orf
        /// </summary>
        public static readonly Region EU_MADRID_3 = new Region(
            "eu-madrid-3", "orf", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-marseille-1, RegionKey: mrs
        /// </summary>
        public static readonly Region EU_MARSEILLE_1 = new Region(
            "eu-marseille-1", "mrs", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-milan-1, RegionKey: lin
        /// </summary>
        public static readonly Region EU_MILAN_1 = new Region(
            "eu-milan-1", "lin", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-paris-1, RegionKey: cdg
        /// </summary>
        public static readonly Region EU_PARIS_1 = new Region(
            "eu-paris-1", "cdg", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-stockholm-1, RegionKey: arn
        /// </summary>
        public static readonly Region EU_STOCKHOLM_1 = new Region(
            "eu-stockholm-1", "arn", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-turin-1, RegionKey: nrq
        /// </summary>
        public static readonly Region EU_TURIN_1 = new Region(
            "eu-turin-1", "nrq", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: eu-zurich-1, RegionKey: zrh
        /// </summary>
        public static readonly Region EU_ZURICH_1 = new Region(
            "eu-zurich-1", "zrh", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: il-jerusalem-1, RegionKey: mtz
        /// </summary>
        public static readonly Region IL_JERUSALEM_1 = new Region(
            "il-jerusalem-1", "mtz", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: me-abudhabi-1, RegionKey: auh
        /// </summary>
        public static readonly Region ME_ABUDHABI_1 = new Region(
            "me-abudhabi-1", "auh", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: me-dubai-1, RegionKey: dxb
        /// </summary>
        public static readonly Region ME_DUBAI_1 = new Region(
            "me-dubai-1", "dxb", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: me-jeddah-1, RegionKey: jed
        /// </summary>
        public static readonly Region ME_JEDDAH_1 = new Region(
            "me-jeddah-1", "jed", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: me-riyadh-1, RegionKey: ruh
        /// </summary>
        public static readonly Region ME_RIYADH_1 = new Region(
            "me-riyadh-1", "ruh", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: mx-monterrey-1, RegionKey: mty
        /// </summary>
        public static readonly Region MX_MONTERREY_1 = new Region(
            "mx-monterrey-1", "mty", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: mx-queretaro-1, RegionKey: qro
        /// </summary>
        public static readonly Region MX_QUERETARO_1 = new Region(
            "mx-queretaro-1", "qro", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: sa-bogota-1, RegionKey: bog
        /// </summary>
        public static readonly Region SA_BOGOTA_1 = new Region(
            "sa-bogota-1", "bog", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: sa-riodejaneiro-2, RegionKey: swq
        /// </summary>
        public static readonly Region SA_RIODEJANEIRO_2 = new Region(
            "sa-riodejaneiro-2", "swq", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: sa-santiago-1, RegionKey: scl
        /// </summary>
        public static readonly Region SA_SANTIAGO_1 = new Region(
            "sa-santiago-1", "scl", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: sa-saopaulo-1, RegionKey: gru
        /// </summary>
        public static readonly Region SA_SAOPAULO_1 = new Region(
            "sa-saopaulo-1", "gru", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: sa-valparaiso-1, RegionKey: vap
        /// </summary>
        public static readonly Region SA_VALPARAISO_1 = new Region(
            "sa-valparaiso-1", "vap", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: sa-vinhedo-1, RegionKey: vcp
        /// </summary>
        public static readonly Region SA_VINHEDO_1 = new Region(
            "sa-vinhedo-1", "vcp", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: uk-cardiff-1, RegionKey: cwl
        /// </summary>
        public static readonly Region UK_CARDIFF_1 = new Region(
            "uk-cardiff-1", "cwl", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: uk-london-1, RegionKey: lhr
        /// </summary>
        public static readonly Region UK_LONDON_1 = new Region(
            "uk-london-1", "lhr", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-abilene-1, RegionKey: abl
        /// </summary>
        public static readonly Region US_ABILENE_1 = new Region(
            "us-abilene-1", "abl", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-ashburn-1, RegionKey: iad
        /// </summary>
        public static readonly Region US_ASHBURN_1 = new Region(
            "us-ashburn-1", "iad", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-boardman-1, RegionKey: nhj
        /// </summary>
        public static readonly Region US_BOARDMAN_1 = new Region(
            "us-boardman-1", "nhj", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-chicago-1, RegionKey: ord
        /// </summary>
        public static readonly Region US_CHICAGO_1 = new Region(
            "us-chicago-1", "ord", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-columbus-1, RegionKey: vkz
        /// </summary>
        public static readonly Region US_COLUMBUS_1 = new Region(
            "us-columbus-1", "vkz", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-dallas-1, RegionKey: dfw
        /// </summary>
        public static readonly Region US_DALLAS_1 = new Region(
            "us-dallas-1", "dfw", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-desmoines-1, RegionKey: kqq
        /// </summary>
        public static readonly Region US_DESMOINES_1 = new Region(
            "us-desmoines-1", "kqq", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-lenexa-1, RegionKey: lxo
        /// </summary>
        public static readonly Region US_LENEXA_1 = new Region(
            "us-lenexa-1", "lxo", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-phoenix-1, RegionKey: phx
        /// </summary>
        public static readonly Region US_PHOENIX_1 = new Region(
            "us-phoenix-1", "phx", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-quincy-1, RegionKey: eem
        /// </summary>
        public static readonly Region US_QUINCY_1 = new Region(
            "us-quincy-1", "eem", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-saltlake-2, RegionKey: aga
        /// </summary>
        public static readonly Region US_SALTLAKE_2 = new Region(
            "us-saltlake-2", "aga", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-sanantonio-1, RegionKey: fbb
        /// </summary>
        public static readonly Region US_SANANTONIO_1 = new Region(
            "us-sanantonio-1", "fbb", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-sanjose-1, RegionKey: sjc
        /// </summary>
        public static readonly Region US_SANJOSE_1 = new Region(
            "us-sanjose-1", "sjc", OC1);

        /// <summary>
        /// Realm: OC1, RegionID: us-shawnee-1, RegionKey: drz
        /// </summary>
        public static readonly Region US_SHAWNEE_1 = new Region(
            "us-shawnee-1", "drz", OC1);

        /// <summary>
        /// Realm: OC2, RegionID: us-langley-1, RegionKey: lfi
        /// </summary>
        public static readonly Region US_LANGLEY_1 = new Region(
            "us-langley-1", "lfi", OC2);

        /// <summary>
        /// Realm: OC2, RegionID: us-luke-1, RegionKey: luf
        /// </summary>
        public static readonly Region US_LUKE_1 = new Region(
            "us-luke-1", "luf", OC2);

        /// <summary>
        /// Realm: OC3, RegionID: us-gov-ashburn-1, RegionKey: ric
        /// </summary>
        public static readonly Region US_GOV_ASHBURN_1 = new Region(
            "us-gov-ashburn-1", "ric", OC3);

        /// <summary>
        /// Realm: OC3, RegionID: us-gov-chicago-1, RegionKey: pia
        /// </summary>
        public static readonly Region US_GOV_CHICAGO_1 = new Region(
            "us-gov-chicago-1", "pia", OC3);

        /// <summary>
        /// Realm: OC3, RegionID: us-gov-phoenix-1, RegionKey: tus
        /// </summary>
        public static readonly Region US_GOV_PHOENIX_1 = new Region(
            "us-gov-phoenix-1", "tus", OC3);

        /// <summary>
        /// Realm: OC4, RegionID: uk-gov-cardiff-1, RegionKey: brs
        /// </summary>
        public static readonly Region UK_GOV_CARDIFF_1 = new Region(
            "uk-gov-cardiff-1", "brs", OC4);

        /// <summary>
        /// Realm: OC4, RegionID: uk-gov-london-1, RegionKey: ltn
        /// </summary>
        public static readonly Region UK_GOV_LONDON_1 = new Region(
            "uk-gov-london-1", "ltn", OC4);

        /// <summary>
        /// Realm: OC5, RegionID: us-tacoma-1, RegionKey: tiw
        /// </summary>
        public static readonly Region US_TACOMA_1 = new Region(
            "us-tacoma-1", "tiw", OC5);

        /// <summary>
        /// Realm: OC6, RegionID: us-gov-fortworth-1, RegionKey: ftw
        /// </summary>
        public static readonly Region US_GOV_FORTWORTH_1 = new Region(
            "us-gov-fortworth-1", "ftw", OC6);

        /// <summary>
        /// Realm: OC6, RegionID: us-gov-sterling-2, RegionKey: dca
        /// </summary>
        public static readonly Region US_GOV_STERLING_2 = new Region(
            "us-gov-sterling-2", "dca", OC6);

        /// <summary>
        /// Realm: OC8, RegionID: ap-chiyoda-1, RegionKey: nja
        /// </summary>
        public static readonly Region AP_CHIYODA_1 = new Region(
            "ap-chiyoda-1", "nja", OC8);

        /// <summary>
        /// Realm: OC8, RegionID: ap-ibaraki-1, RegionKey: ukb
        /// </summary>
        public static readonly Region AP_IBARAKI_1 = new Region(
            "ap-ibaraki-1", "ukb", OC8);

        /// <summary>
        /// Realm: OC9, RegionID: me-dcc-muscat-1, RegionKey: mct
        /// </summary>
        public static readonly Region ME_DCC_MUSCAT_1 = new Region(
            "me-dcc-muscat-1", "mct", OC9);

        /// <summary>
        /// Realm: OC9, RegionID: me-ibri-1, RegionKey: ibr
        /// </summary>
        public static readonly Region ME_IBRI_1 = new Region(
            "me-ibri-1", "ibr", OC9);

        /// <summary>
        /// Realm: OC10, RegionID: ap-dcc-canberra-1, RegionKey: wga
        /// </summary>
        public static readonly Region AP_DCC_CANBERRA_1 = new Region(
            "ap-dcc-canberra-1", "wga", OC10);

        /// <summary>
        /// Realm: OC11, RegionID: us-gov-fortworth-3, RegionKey: dal
        /// </summary>
        public static readonly Region US_GOV_FORTWORTH_3 = new Region(
            "us-gov-fortworth-3", "dal", OC11);

        /// <summary>
        /// Realm: OC11, RegionID: us-gov-phoenix-3, RegionKey: gyr
        /// </summary>
        public static readonly Region US_GOV_PHOENIX_3 = new Region(
            "us-gov-phoenix-3", "gyr", OC11);

        /// <summary>
        /// Realm: OC11, RegionID: us-gov-sterling-3, RegionKey: hef
        /// </summary>
        public static readonly Region US_GOV_STERLING_3 = new Region(
            "us-gov-sterling-3", "hef", OC11);

        /// <summary>
        /// Realm: OC12, RegionID: us-gov-ashburn-2, RegionKey: okv
        /// </summary>
        public static readonly Region US_GOV_ASHBURN_2 = new Region(
            "us-gov-ashburn-2", "okv", OC12);

        /// <summary>
        /// Realm: OC12, RegionID: us-gov-phoenix-2, RegionKey: geu
        /// </summary>
        public static readonly Region US_GOV_PHOENIX_2 = new Region(
            "us-gov-phoenix-2", "geu", OC12);

        /// <summary>
        /// Realm: OC12, RegionID: us-gov-saltlake-1, RegionKey: vel
        /// </summary>
        public static readonly Region US_GOV_SALTLAKE_1 = new Region(
            "us-gov-saltlake-1", "vel", OC12);

        /// <summary>
        /// Realm: OC14, RegionID: eu-dcc-dublin-1, RegionKey: ork
        /// </summary>
        public static readonly Region EU_DCC_DUBLIN_1 = new Region(
            "eu-dcc-dublin-1", "ork", OC14);

        /// <summary>
        /// Realm: OC14, RegionID: eu-dcc-dublin-2, RegionKey: snn
        /// </summary>
        public static readonly Region EU_DCC_DUBLIN_2 = new Region(
            "eu-dcc-dublin-2", "snn", OC14);

        /// <summary>
        /// Realm: OC14, RegionID: eu-dcc-milan-1, RegionKey: bgy
        /// </summary>
        public static readonly Region EU_DCC_MILAN_1 = new Region(
            "eu-dcc-milan-1", "bgy", OC14);

        /// <summary>
        /// Realm: OC14, RegionID: eu-dcc-milan-2, RegionKey: mxp
        /// </summary>
        public static readonly Region EU_DCC_MILAN_2 = new Region(
            "eu-dcc-milan-2", "mxp", OC14);

        /// <summary>
        /// Realm: OC14, RegionID: eu-dcc-rating-1, RegionKey: dus
        /// </summary>
        public static readonly Region EU_DCC_RATING_1 = new Region(
            "eu-dcc-rating-1", "dus", OC14);

        /// <summary>
        /// Realm: OC14, RegionID: eu-dcc-rating-2, RegionKey: dtm
        /// </summary>
        public static readonly Region EU_DCC_RATING_2 = new Region(
            "eu-dcc-rating-2", "dtm", OC14);

        /// <summary>
        /// Realm: OC15, RegionID: ap-dcc-gazipur-1, RegionKey: dac
        /// </summary>
        public static readonly Region AP_DCC_GAZIPUR_1 = new Region(
            "ap-dcc-gazipur-1", "dac", OC15);

        /// <summary>
        /// Realm: OC16, RegionID: us-sanjose-2, RegionKey: qkl
        /// </summary>
        public static readonly Region US_SANJOSE_2 = new Region(
            "us-sanjose-2", "qkl", OC16);

        /// <summary>
        /// Realm: OC16, RegionID: us-westjordan-1, RegionKey: sgu
        /// </summary>
        public static readonly Region US_WESTJORDAN_1 = new Region(
            "us-westjordan-1", "sgu", OC16);

        /// <summary>
        /// Realm: OC17, RegionID: us-dcc-phoenix-1, RegionKey: ifp
        /// </summary>
        public static readonly Region US_DCC_PHOENIX_1 = new Region(
            "us-dcc-phoenix-1", "ifp", OC17);

        /// <summary>
        /// Realm: OC17, RegionID: us-dcc-phoenix-2, RegionKey: gcn
        /// </summary>
        public static readonly Region US_DCC_PHOENIX_2 = new Region(
            "us-dcc-phoenix-2", "gcn", OC17);

        /// <summary>
        /// Realm: OC17, RegionID: us-dcc-phoenix-4, RegionKey: yum
        /// </summary>
        public static readonly Region US_DCC_PHOENIX_4 = new Region(
            "us-dcc-phoenix-4", "yum", OC17);

        /// <summary>
        /// Realm: OC19, RegionID: eu-frankfurt-2, RegionKey: str
        /// </summary>
        public static readonly Region EU_FRANKFURT_2 = new Region(
            "eu-frankfurt-2", "str", OC19);

        /// <summary>
        /// Realm: OC19, RegionID: eu-madrid-2, RegionKey: vll
        /// </summary>
        public static readonly Region EU_MADRID_2 = new Region(
            "eu-madrid-2", "vll", OC19);

        /// <summary>
        /// Realm: OC20, RegionID: eu-jovanovac-1, RegionKey: beg
        /// </summary>
        public static readonly Region EU_JOVANOVAC_1 = new Region(
            "eu-jovanovac-1", "beg", OC20);

        /// <summary>
        /// Realm: OC21, RegionID: me-alrayyan-1, RegionKey: vve
        /// </summary>
        public static readonly Region ME_ALRAYYAN_1 = new Region(
            "me-alrayyan-1", "vve", OC21);

        /// <summary>
        /// Realm: OC21, RegionID: me-dcc-doha-1, RegionKey: doh
        /// </summary>
        public static readonly Region ME_DCC_DOHA_1 = new Region(
            "me-dcc-doha-1", "doh", OC21);

        /// <summary>
        /// Realm: OC22, RegionID: eu-dcc-rome-1, RegionKey: nap
        /// </summary>
        public static readonly Region EU_DCC_ROME_1 = new Region(
            "eu-dcc-rome-1", "nap", OC22);

        /// <summary>
        /// Realm: OC22, RegionID: eu-milan-2, RegionKey: pbv
        /// </summary>
        public static readonly Region EU_MILAN_2 = new Region(
            "eu-milan-2", "pbv", OC22);

        /// <summary>
        /// Realm: OC23, RegionID: us-somerset-1, RegionKey: ebb
        /// </summary>
        public static readonly Region US_SOMERSET_1 = new Region(
            "us-somerset-1", "ebb", OC23);

        /// <summary>
        /// Realm: OC23, RegionID: us-thames-1, RegionKey: ebl
        /// </summary>
        public static readonly Region US_THAMES_1 = new Region(
            "us-thames-1", "ebl", OC23);

        /// <summary>
        /// Realm: OC24, RegionID: eu-crissier-1, RegionKey: avf
        /// </summary>
        public static readonly Region EU_CRISSIER_1 = new Region(
            "eu-crissier-1", "avf", OC24);

        /// <summary>
        /// Realm: OC24, RegionID: eu-dcc-zurich-1, RegionKey: avz
        /// </summary>
        public static readonly Region EU_DCC_ZURICH_1 = new Region(
            "eu-dcc-zurich-1", "avz", OC24);

        /// <summary>
        /// Realm: OC25, RegionID: ap-dcc-osaka-1, RegionKey: uky
        /// </summary>
        public static readonly Region AP_DCC_OSAKA_1 = new Region(
            "ap-dcc-osaka-1", "uky", OC25);

        /// <summary>
        /// Realm: OC25, RegionID: ap-dcc-tokyo-1, RegionKey: tyo
        /// </summary>
        public static readonly Region AP_DCC_TOKYO_1 = new Region(
            "ap-dcc-tokyo-1", "tyo", OC25);

        /// <summary>
        /// Realm: OC26, RegionID: me-abudhabi-3, RegionKey: ahu
        /// </summary>
        public static readonly Region ME_ABUDHABI_3 = new Region(
            "me-abudhabi-3", "ahu", OC26);

        /// <summary>
        /// Realm: OC26, RegionID: me-alain-1, RegionKey: rba
        /// </summary>
        public static readonly Region ME_ALAIN_1 = new Region(
            "me-alain-1", "rba", OC26);

        /// <summary>
        /// Realm: OC27, RegionID: us-dcc-swjordan-1, RegionKey: ozz
        /// </summary>
        public static readonly Region US_DCC_SWJORDAN_1 = new Region(
            "us-dcc-swjordan-1", "ozz", OC27);

        /// <summary>
        /// Realm: OC28, RegionID: us-dcc-swjordan-2, RegionKey: drs
        /// </summary>
        public static readonly Region US_DCC_SWJORDAN_2 = new Region(
            "us-dcc-swjordan-2", "drs", OC28);

        /// <summary>
        /// Realm: OC29, RegionID: me-abudhabi-2, RegionKey: rkt
        /// </summary>
        public static readonly Region ME_ABUDHABI_2 = new Region(
            "me-abudhabi-2", "rkt", OC29);

        /// <summary>
        /// Realm: OC29, RegionID: me-abudhabi-4, RegionKey: shj
        /// </summary>
        public static readonly Region ME_ABUDHABI_4 = new Region(
            "me-abudhabi-4", "shj", OC29);

        /// <summary>
        /// Realm: OC31, RegionID: ap-hobsonville-1, RegionKey: izq
        /// </summary>
        public static readonly Region AP_HOBSONVILLE_1 = new Region(
            "ap-hobsonville-1", "izq", OC31);

        /// <summary>
        /// Realm: OC31, RegionID: ap-silverdale-1, RegionKey: jjt
        /// </summary>
        public static readonly Region AP_SILVERDALE_1 = new Region(
            "ap-silverdale-1", "jjt", OC31);

        /// <summary>
        /// Realm: OC32, RegionID: ap-olympic-1, RegionKey: zzm
        /// </summary>
        public static readonly Region AP_OLYMPIC_1 = new Region(
            "ap-olympic-1", "zzm", OC32);

        /// <summary>
        /// Realm: OC35, RegionID: ap-chuncheon-2, RegionKey: bno
        /// </summary>
        public static readonly Region AP_CHUNCHEON_2 = new Region(
            "ap-chuncheon-2", "bno", OC35);

        /// <summary>
        /// Realm: OC35, RegionID: ap-seoul-2, RegionKey: dtz
        /// </summary>
        public static readonly Region AP_SEOUL_2 = new Region(
            "ap-seoul-2", "dtz", OC35);

        /// <summary>
        /// Realm: OC35, RegionID: ap-suwon-1, RegionKey: dln
        /// </summary>
        public static readonly Region AP_SUWON_1 = new Region(
            "ap-suwon-1", "dln", OC35);

        /// <summary>
        /// Realm: OC36, RegionID: me-alkhobar-1, RegionKey: dam
        /// </summary>
        public static readonly Region ME_ALKHOBAR_1 = new Region(
            "me-alkhobar-1", "dam", OC36);

        /// <summary>
        /// Realm: OC36, RegionID: me-riyadh-2, RegionKey: kzq
        /// </summary>
        public static readonly Region ME_RIYADH_2 = new Region(
            "me-riyadh-2", "kzq", OC36);

        /// <summary>
        /// Realm: OC39, RegionID: us-tukwila-3, RegionKey: nbq
        /// </summary>
        public static readonly Region US_TUKWILA_3 = new Region(
            "us-tukwila-3", "nbq", OC39);

        /// <summary>
        /// Realm: OC40, RegionID: ap-osaka-2, RegionKey: ibg
        /// </summary>
        public static readonly Region AP_OSAKA_2 = new Region(
            "ap-osaka-2", "ibg", OC40);

        /// <summary>
        /// Realm: OC40, RegionID: ap-tatebayashi-1, RegionKey: jbb
        /// </summary>
        public static readonly Region AP_TATEBAYASHI_1 = new Region(
            "ap-tatebayashi-1", "jbb", OC40);

        /// <summary>
        /// Realm: OC41, RegionID: me-dubai-2, RegionKey: abr
        /// </summary>
        public static readonly Region ME_DUBAI_2 = new Region(
            "me-dubai-2", "abr", OC41);

        /// <summary>
        /// Realm: OC41, RegionID: me-dubai-3, RegionKey: pcz
        /// </summary>
        public static readonly Region ME_DUBAI_3 = new Region(
            "me-dubai-3", "pcz", OC41);

        /// <summary>
        /// Realm: OC42, RegionID: us-ashburn-2, RegionKey: yxj
        /// </summary>
        public static readonly Region US_ASHBURN_2 = new Region(
            "us-ashburn-2", "yxj", OC42);

        /// <summary>
        /// Realm: OC42, RegionID: us-newark-1, RegionKey: pgc
        /// </summary>
        public static readonly Region US_NEWARK_1 = new Region(
            "us-newark-1", "pgc", OC42);

        /// <summary>
        /// Realm: OC43, RegionID: ap-pathumthani-1, RegionKey: mez
        /// </summary>
        public static readonly Region AP_PATHUMTHANI_1 = new Region(
            "ap-pathumthani-1", "mez", OC43);

        /// <summary>
        /// Realm: OC43, RegionID: ap-samutprakan-1, RegionKey: yik
        /// </summary>
        public static readonly Region AP_SAMUTPRAKAN_1 = new Region(
            "ap-samutprakan-1", "yik", OC43);

        /// <summary>
        /// Realm: OC45, RegionID: me-sabahiya-1, RegionKey: ayz
        /// </summary>
        public static readonly Region ME_SABAHIYA_1 = new Region(
            "me-sabahiya-1", "ayz", OC45);

        /// <summary>
        /// Realm: OC46, RegionID: uk-london-2, RegionKey: den
        /// </summary>
        public static readonly Region UK_LONDON_2 = new Region(
            "uk-london-2", "den", OC46);

        /// <summary>
        /// Realm: OC47, RegionID: uk-london-3, RegionKey: kal
        /// </summary>
        public static readonly Region UK_LONDON_3 = new Region(
            "uk-london-3", "kal", OC47);

        /// <summary>
        /// Realm: OC47, RegionID: uk-london-4, RegionKey: pyz
        /// </summary>
        public static readonly Region UK_LONDON_4 = new Region(
            "uk-london-4", "pyz", OC47);

        /// <summary>
        /// Realm: OC50, RegionID: ap-kyoto-1, RegionKey: suf
        /// </summary>
        public static readonly Region AP_KYOTO_1 = new Region(
            "ap-kyoto-1", "suf", OC50);

        /// <summary>
        /// Realm: OC50, RegionID: ap-mitaka-1, RegionKey: mfq
        /// </summary>
        public static readonly Region AP_MITAKA_1 = new Region(
            "ap-mitaka-1", "mfq", OC50);

        /// <summary>
        /// Realm: OC51, RegionID: eu-budapest-1, RegionKey: jsk
        /// </summary>
        public static readonly Region EU_BUDAPEST_1 = new Region(
            "eu-budapest-1", "jsk", OC51);

        /// <summary>
        /// Realm: OC52, RegionID: sa-riodejaneiro-1, RegionKey: hnw
        /// </summary>
        public static readonly Region SA_RIODEJANEIRO_1 = new Region(
            "sa-riodejaneiro-1", "hnw", OC52);

        /// <summary>
        /// Realm: OC54, RegionID: sa-belenzinho-1, RegionKey: trx
        /// </summary>
        public static readonly Region SA_BELENZINHO_1 = new Region(
            "sa-belenzinho-1", "trx", OC54);

        /// <summary>
        /// Realm: OC54, RegionID: sa-saopaulo-3, RegionKey: lmp
        /// </summary>
        public static readonly Region SA_SAOPAULO_3 = new Region(
            "sa-saopaulo-3", "lmp", OC54);

        /// <summary>
        /// Realm: OC55, RegionID: ap-eastosaka-1, RegionKey: dqf
        /// </summary>
        public static readonly Region AP_EASTOSAKA_1 = new Region(
            "ap-eastosaka-1", "dqf", OC55);

        /// <summary>
        /// Realm: OC55, RegionID: ap-westtokyo-1, RegionKey: zwe
        /// </summary>
        public static readonly Region AP_WESTTOKYO_1 = new Region(
            "ap-westtokyo-1", "zwe", OC55);

        /// <summary>
        /// Realm: OC57, RegionID: me-abudhabi-5, RegionKey: jhz
        /// </summary>
        public static readonly Region ME_ABUDHABI_5 = new Region(
            "me-abudhabi-5", "jhz", OC57);

        /// <summary>
        /// Realm: OC57, RegionID: me-dubai-4, RegionKey: zqa
        /// </summary>
        public static readonly Region ME_DUBAI_4 = new Region(
            "me-dubai-4", "zqa", OC57);

        /// <summary>
        /// Realm: OC60, RegionID: us-tukwila-5, RegionKey: xad
        /// </summary>
        public static readonly Region US_TUKWILA_5 = new Region(
            "us-tukwila-5", "xad", OC60);

        /// <summary>
        /// Realm: OC61, RegionID: us-tukwila-6, RegionKey: xab
        /// </summary>
        public static readonly Region US_TUKWILA_6 = new Region(
            "us-tukwila-6", "xab", OC61);

        /// <summary>
        /// Realm: OC62, RegionID: us-tukwila-7, RegionKey: xac
        /// </summary>
        public static readonly Region US_TUKWILA_7 = new Region(
            "us-tukwila-7", "xac", OC62);

        /// <summary>
        /// Realm: OC64, RegionID: ap-tokyo-2, RegionKey: jcu
        /// </summary>
        public static readonly Region AP_TOKYO_2 = new Region(
            "ap-tokyo-2", "jcu", OC64);

        /// <summary>
        /// Realm: OC88, RegionID: ap-olympic-2, RegionKey: jdx
        /// </summary>
        public static readonly Region AP_OLYMPIC_2 = new Region(
            "ap-olympic-2", "jdx", OC88);

        // === End autogenerated regions ===

    }
}
